#!/usr/bin/env python3
"""Generate the checked-in HTTP route inventory from the Flask application."""

from __future__ import annotations

import argparse
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from flask import Flask
from werkzeug.routing import Rule

from posetestbot.web.app import app


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "docs" / "reference" / "http-api-routes.md"
IGNORED_ENDPOINTS = {"static"}


@dataclass(frozen=True)
class RouteRecord:
    group: str
    methods: str
    path: str
    interface: str
    purpose: str
    endpoint: str


def _group(path: str) -> str:
    prefixes = (
        ("/bop/", "BOP annotation and evaluation"),
        ("/calibration-targets", "Calibration targets"),
        ("/calibration/", "Calibration"),
        ("/capture", "Capture"),
        ("/cluster/", "External cluster controller proxy"),
        ("/jobs", "Local jobs and commands"),
        ("/run-command", "Local jobs and commands"),
        ("/monitoring/", "Monitoring"),
        ("/pipeline/", "Pipeline"),
        ("/pose-templates/", "Pose templates"),
        ("/robot/", "System status"),
        ("/run-config", "Pipeline"),
        ("/runtime/", "System status"),
        ("/sensors/", "Sensors"),
        ("/sync/", "Synchronization"),
        ("/system/", "System lifecycle"),
        ("/ui/", "Operator-console data"),
        ("/workpieces/", "Workpiece Catalogue"),
        ("/hardware/", "System status"),
    )
    for prefix, name in prefixes:
        if path.startswith(prefix):
            return name
    return "Operator console and static assets"


INTERFACE_OVERRIDES = {
    "calibration_targets.calibration_target_preview": "PNG",
    "jobs_commands.get_job_log": "Text",
    "pose_templates.library_thumbnail": "JSON",
    "pose_templates.workpiece_orientation_thumbnail": "JSON",
    "ui.ui_cell_camera_frame": "PNG",
    "workpieces.workpiece_catalog_export": "File",
}


def _interface(path: str, endpoint: str) -> str:
    if endpoint in INTERFACE_OVERRIDES:
        return INTERFACE_OVERRIDES[endpoint]
    if path == "/":
        return "HTML"
    if path.endswith(".png"):
        return "PNG"
    if path.endswith(".jpg"):
        return "JPEG"
    if path.endswith(".svg"):
        return "SVG"
    if "/download" in path or endpoint.endswith(
        (
            "_asset",
            "_download",
            "_image",
            "_log",
            "_pdf",
            "_report",
        )
    ):
        return "File"
    return "JSON"


PURPOSE_OVERRIDES = {
    "brand_asset": "Serve an operator-console brand asset",
    "hri_cell_template": "Serve the fixed HRI cell SVG",
    "pages.index": "Serve the bundled operator console",
}


def _purpose(endpoint: str) -> str:
    if endpoint in PURPOSE_OVERRIDES:
        return PURPOSE_OVERRIDES[endpoint]
    function_name = endpoint.rsplit(".", maxsplit=1)[-1]
    for suffix in ("_endpoint", "_response"):
        if function_name.endswith(suffix):
            function_name = function_name[: -len(suffix)]
    return function_name.replace("_", " ").capitalize()


def route_records(application: Flask) -> list[RouteRecord]:
    records: list[RouteRecord] = []
    rules: Iterable[Rule] = application.url_map.iter_rules()
    for rule in rules:
        if rule.endpoint in IGNORED_ENDPOINTS:
            continue
        methods = sorted(set(rule.methods or ()) - {"HEAD", "OPTIONS"})
        records.append(
            RouteRecord(
                group=_group(rule.rule),
                methods=", ".join(methods),
                path=rule.rule,
                interface=_interface(rule.rule, rule.endpoint),
                purpose=_purpose(rule.endpoint),
                endpoint=rule.endpoint,
            )
        )
    return sorted(records, key=lambda item: (item.group, item.path, item.methods))


def render_route_index(application: Flask) -> str:
    records = route_records(application)
    grouped: dict[str, list[RouteRecord]] = defaultdict(list)
    for record in records:
        grouped[record.group].append(record)

    lines = [
        "<!-- Generated by scripts/generate_http_api_reference.py; do not edit. -->",
        "",
        "# Complete HTTP route index",
        "",
        f"This index contains all **{len(records)}** non-static Flask rules registered by",
        "`posetestbot.web.app.create_app`. It is generated from the running route map,",
        "so aliases and mixed-method rules appear exactly as Flask exposes them.",
        "",
        "The index describes reachability and transport type. Request bodies, state",
        "transitions, safety gates, and response semantics are documented in the",
        "[domain API guides](http-api.md). The implicit Flask `/static/<path:filename>`",
        "handler is intentionally excluded.",
        "",
        "Regenerate after changing a route:",
        "",
        "```bash",
        "uv run python scripts/generate_http_api_reference.py --write",
        "uv run python scripts/generate_http_api_reference.py --check",
        "```",
        "",
    ]
    for group in sorted(grouped):
        lines.extend(
            [
                f"## {group}",
                "",
                "| Method | Path | Returns | Purpose | Flask endpoint |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        for record in grouped[group]:
            lines.append(
                "| "
                + " | ".join(
                    (
                        f"`{record.methods}`",
                        f"`{record.path}`",
                        record.interface,
                        record.purpose,
                        f"`{record.endpoint}`",
                    )
                )
                + " |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true", help="replace the generated file")
    action.add_argument("--check", action="store_true", help="fail if the file is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    output = arguments.output.resolve()
    rendered = render_route_index(app)
    if arguments.check:
        try:
            current = output.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = None
        if current != rendered:
            print(
                f"{output} is stale; run "
                "`uv run python scripts/generate_http_api_reference.py --write`."
            )
            return 1
        print(f"HTTP route reference is current ({len(route_records(app))} routes).")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {output} ({len(route_records(app))} routes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
