"""Canonical artifact names used by current scripts and rewrite modules."""

from __future__ import annotations

RAW_ROBOT_EE_POSES = "raw_robot_ee_poses.json"
MATCH_ROBOT_EE_POSES = "match_robot_ee_poses.json"
ARUCO_POSE_ESTIMATION = "aruco_pose_estimation.json"
ARUCO_DETECTIONS = "aruco_detections.json"
CHARUCO_POSE_ESTIMATION = "charuco_pose_estimation.json"
CHECKERBOARD_POSE_ESTIMATION = "checkerboard_pose_estimation.json"
CALIBRATION_TARGET_POSE_ESTIMATION = "calibration_target_pose_estimation.json"
ARUCO_COVERAGE_REPORT = "aruco_coverage_report.json"
CAM_K = "cam_K.txt"
DEPTH_SCALE = "depthscale.txt"
CAMERA_JSON = "camera.json"
CAMERA_DATA_JSON = "camera_data.json"
FRAME_METADATA_JSONL = "frame_metadata.jsonl"
DATASET_MANIFEST = "dataset_manifest.json"
RUN_CONFIG = "run_config.json"
RUN_PREFLIGHT_REPORT = "run_preflight_report.json"
REWRITE_GATE_REPORT = "rewrite_gate_report.json"
REWRITE_STATUS_REPORT = "rewrite_status_report.json"
HARDWARE_STATUS_REPORT = "hardware_status_report.json"
CAPTURE_PLAN = "capture_plan.json"
CAPTURE_PLAN_PREFLIGHT_REPORT = "capture_plan_preflight_report.json"
CAPTURE_EXECUTION_PLAN = "capture_execution_plan.json"
CAPTURE_EXECUTION_STATUS = "capture_execution_status.json"
CAPTURE_EXECUTION_REPORT = "capture_execution_report.json"
CAPTURE_EXECUTION_LOGS_DIR = "capture_execution_logs"
REALSENSE_CAPTURE_SMOKE_REPORT = "realsense_capture_smoke_report.json"
SYNC_REPORT = "sync_report.json"
SYNC_QUALITY_REPORT = "sync_quality_report.json"
BLENDERPROC_RENDER_PLAN = "blenderproc_render_plan.json"
POSE_TEMPLATE_SELECTION = "pose_template_selection.json"
OBJECT_INSTANCES = "object_instances.json"
PIPELINE_SEQUENCE_PLAN = "pipeline_sequence_plan.json"
BOP_EXPORT_MANIFEST = "bop_export_manifest.json"
BOP_FRAME_MAP_JSON = "posetestbot_bop_frame_map.json"
BOP_DATASET_INFO = "dataset_info.json"
BOP_TARGETS_BOP19 = "test_targets_bop19.json"
BOP_MULTIVIEW_TARGETS = "posetestbot_multiview_targets.json"
BOP_COCO_ANNOTATIONS = "posetestbot_coco_annotations.json"
BOP_POSE_TEMPLATE = "posetestbot_pose_template.json"
BOP_INSTANCE_MAP = "posetestbot_instance_map.json"
CALIBRATION_PROFILES = "calibration_profiles.json"
CALIBRATION_PROFILE_SELECTION = "calibration_profile_selection.json"
CALIBRATION_TARGET = "calibration_target.json"
INTRINSIC_CALIBRATION_PROFILES = "intrinsic_calibration_profiles.json"
INTRINSIC_COMPARISON = "intrinsic_comparison.json"
CAMERA_RECTIFICATION_REPORT = "camera_rectification_report.json"
CALIBRATION_OBSERVATIONS = "calibration_observations.json"
CALIBRATION_CANDIDATES = "calibration_candidates.json"
CALIBRATION_PROFILES_FROM_OBSERVATIONS = "calibration_profiles_from_observations.json"
CALIBRATION_SOLVER_REPORT = "calibration_solver_report.json"
CALIBRATION_PROFILES_SOLVED = "calibration_profiles_solved.json"
CALIBRATION_VALIDATION_REPORT = "calibration_validation_report.json"
CALIBRATION_PREFLIGHT_REPORT = "calibration_preflight_report.json"
DERIVED_CAMERA_EE_TRANSFORM = "camera_ee_transform_from_calibration_profiles.json"

LEGACY_SENSOR_METADATA_ARTIFACTS = (
    CAM_K,
    DEPTH_SCALE,
    CAMERA_JSON,
    CAMERA_DATA_JSON,
    FRAME_METADATA_JSONL,
)

RGB_DIR = "rgb"
DEPTH_DIR = "depth"
MASKS_DIR = "masks"
BOP_DIR = "bop"
MODELS_DIR = "models"
CALIBRATION_DIR = "calibration"
PROCESSED_DIR = "processed"
SYNCHRONIZED_DIR = "synchronized"
